version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: niqactivate
    ports:
      - "3306:3306"
  niq-activate-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
